#include "nsISupports.idl"
#include "nsIVariant.idl"

[scriptable, uuid(7b77dabb-b47c-4e2e-a370-14c2fd361058)]
interface ssISiteManager: nsISupports
{
	nsIVariant getSites();
	/*
	nsIVariant getSite(in long index);

	void addSite(in string url, in AString name, in AString customizeImage);
	void changeSite(in long index, in string url, in AString name, in AString customizeImage);
	void exchangeSite(in long index1, in long index2);
	void removeSite(in long index);

	void refreshSite(in long index);
	*/
};
