#include "nsISupports.idl"
#include "nsIVariant.idl"
#include "nsIFile.idl"

[scriptable, uuid(26D34DF2-BB0A-47EB-8164-EC231647F1BD)]
interface ssIThemes : nsISupports
{
	AString getTheme(in AString name);
	AString getThemes();
	boolean removeTheme(in AString name);
	/**
	 * @return the name of the new theme, '' if failed
	 */
	AString installTheme(in nsIFile theme);

	/**
	 * @data JSON string
	 * @output 1) styles.json; 2) styles.css
	 */
	void setUsData(in AString data);
	AString getUsData();
	AString getUsUrl();
};
